#!/bin/bash

#1
cat /etc/passwd | awk -F: '{print "user " $1 " has id " $3}' > ~/work3.log

#2
echo -e "\nroot pwd info: \n" >> ~/work3.log
chage -l root >> ~/work3.log

#3
echo -e "\ngroups list: \n" >> ~/work3.log
cat /etc/group | awk -F: '{print $1}' >> ~/work3.log

#4
echo "Be careful!" > /etc/skel/readme.txt

#5
useradd u1 -p $(openssl passwd -crypt 12345678)

#6
groupadd g1

#7
usermod -a -G g1 u1

#8
echo -e "\nid info u1: \n" >> ~/work3.log
id u1 >> ~/work3.log

#9
usermod -a -G g1 user

#10
echo -e "\nUsers in group g1: \n" >> ~/work3.log
cat /etc/group | grep g1 | awk -F: '{print $4}' >> ~/work3.log

#11
usermod -s /usr/bin/mc u1

#12
useradd u2 -p $(openssl passwd -crypt 87654321)

#13
mkdir /home/test13
cp ~/work3.log /home/test13/work3-1.log
cp ~/work3.log /home/test13/work3-2.log

#14
groupadd test13_access
usermod -a -G test13_access u1
usermod -a -G test13_access u2
chown u1:test13_access /home/test13
chmod -R 640 /home/test13

#15
mkdir /home/test14
chown u1 /home/test14
chmod 755 /home/test14

#16
cp /bin/nano /home/test14/nano
chmod u+s /home/test14/nano

#17
mkdir /home/test15
touch /home/test15/secret_file
echo "This is trap, bruh" > /home/test15/secret_file
chmod 111 /home/test15/secret_file

